### ISSUE TITLE
Class 'postParser' not found

### ISSUE THREAD

**Issue by amplifier1** [Tanweth/Poll-Box#1]
I get a 500 error if I access 'memberlist.php' and 'showteam.php'

PHP Fatal error:  Class 'postParser' not found in /home/xxxxx/public_html/xxxxx/inc/plugins/asb/modules/poll_box.php on line 156

I deleted those 2 scripts from the ACP (adv sidebox manage scripts) and now I do not get any error.

**Comment by WildcardSearch** [comment]
Looks like it is missing:

``` php
require_once MYBB_ROOT."inc/class_parser.php";
```

Should be on line 156 with 157 being current 156

**Comment by Tanweth** [comment]
I never would've seen it myself since I don't put sideboxes on those pages on my site. But that's why it's helpful to have other users to play around with your plugins and report issues. Change added. Thanks for your report. :)
